version: '3.4'

services:
  pizzaorder:
    image: ${DOCKER_REGISTRY-}pizzaorder
    build:
      context: .
      dockerfile: PizzaOrder/Dockerfile
    depends_on:
     - storage
  storage:
      image: ${DOCKER_REGISTRY-}storage
      build:
        context: .
        dockerfile: StorageApi/Dockerfile
      depends_on:
       - database
  database:
    image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
    ports:
      - "1433:1433"
    environment:
       - ACCEPT_EULA=Y 
       - SA_PASSWORD=Password-1
    volumes:
    - quizdata:/storage/quizzes

volumes:
  quizdata: {}
