version: '3.4'

services:
  pizzaorder:
    image: ${DOCKER_REGISTRY-}pizzaorder
    build:
      context: .
      dockerfile: PizzaOrder/Dockerfile
    depends_on:
     - storage
  storage:
      image: ${DOCKER_REGISTRY-}storage
      build:
        context: .
        dockerfile: StorageApi/Dockerfile
